version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"    
    depends_on:
      - db
    environment:
      postgres: "postgres://postgres:@localhost:5434/postgres"
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres